# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fedsplit_communication.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'fedsplit_communication.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1c\x66\x65\x64split_communication.proto\x12\x16\x66\x65\x64split_communication\"K\n\tEmbedding\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x11\n\tembedding\x18\x02 \x03(\x01\x12\r\n\x05shape\x18\x03 \x03(\x03\x12\x10\n\x08\x65valuate\x18\x04 \x01(\x08\"(\n\tGradients\x12\x0c\n\x04grad\x18\x01 \x03(\x01\x12\r\n\x05shape\x18\x02 \x03(\x03\"_\n\x06Models\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x34\n\tgradients\x18\x02 \x03(\x0b\x32!.fedsplit_communication.Gradients\x12\x13\n\x0b\x64\x61ta_sample\x18\x03 \x01(\x03\"\'\n\x06Logits\x12\x0e\n\x06logits\x18\x01 \x03(\x01\x12\r\n\x05shape\x18\x02 \x03(\x03\"\x07\n\x05\x45mpty2g\n\x0bTrainServer\x12X\n\x10GetTrainResponse\x12!.fedsplit_communication.Embedding\x1a!.fedsplit_communication.Gradients2^\n\tAggregate\x12Q\n\x0f\x41ggregateModels\x12\x1e.fedsplit_communication.Models\x1a\x1e.fedsplit_communication.Models2d\n\x11ReturnServerModel\x12O\n\x0eGetServerModel\x12\x1d.fedsplit_communication.Empty\x1a\x1e.fedsplit_communication.Models2g\n\x08\x42\x61\x63kward\x12[\n\x13GetBackwardResponse\x12!.fedsplit_communication.Gradients\x1a!.fedsplit_communication.Gradients2m\n\x0fSendModelGlobal\x12Z\n\x12ReceiveGlobalModel\x12!.fedsplit_communication.Gradients\x1a!.fedsplit_communication.Gradientsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fedsplit_communication_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMBEDDING']._serialized_start=56
  _globals['_EMBEDDING']._serialized_end=131
  _globals['_GRADIENTS']._serialized_start=133
  _globals['_GRADIENTS']._serialized_end=173
  _globals['_MODELS']._serialized_start=175
  _globals['_MODELS']._serialized_end=270
  _globals['_LOGITS']._serialized_start=272
  _globals['_LOGITS']._serialized_end=311
  _globals['_EMPTY']._serialized_start=313
  _globals['_EMPTY']._serialized_end=320
  _globals['_TRAINSERVER']._serialized_start=322
  _globals['_TRAINSERVER']._serialized_end=425
  _globals['_AGGREGATE']._serialized_start=427
  _globals['_AGGREGATE']._serialized_end=521
  _globals['_RETURNSERVERMODEL']._serialized_start=523
  _globals['_RETURNSERVERMODEL']._serialized_end=623
  _globals['_BACKWARD']._serialized_start=625
  _globals['_BACKWARD']._serialized_end=728
  _globals['_SENDMODELGLOBAL']._serialized_start=730
  _globals['_SENDMODELGLOBAL']._serialized_end=839
# @@protoc_insertion_point(module_scope)
